name: Build and Release Minecraft Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Install dos2unix
      run: sudo apt-get install dos2unix

    - name: Convert line endings
      run: dos2unix gradlew

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build the mod
      run: ./gradlew build

    - name: List build directory
      run: ls -R build/libs

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mod-artifact
        path: build/libs/*.jar

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: mod-artifact

    - name: List downloaded artifacts
      run: ls -R .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Template Mod X.X.X
        draft: true
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: TemplateMod-1.0.0.jar
        asset_name: TemplateMod-1.0.0.jar
        asset_content_type: application/java-archive
